version: "3"
services:
  code-verification-service:
    build: .
    container_name: code-verification-service-container
    cap_add:
      - SYS_PTRACE
    stdin_open: true
    tty: true
    environment:
      DISPLAY: unix${DISPLAY}
    ports:
      - "9873:873"
      - "8080:8080"
    volumes:
      - code-verification-service-src-sync:/root/Elegant/Elegant-Code-Verification-Service:nocopy # nocopy is important
      - cbmc-src-sync:/root/Elegant/CBMC:nocopy
      - /tmp/.X11-unix:/tmp/.X11-unix

# that the important thing
volumes:
  code-verification-service-src-sync:
    external: true
  cbmc-src-sync:
    external: true